version: "3"
services:
  terraria-server:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - terraria-data:/root/.local/share/Terraria/Worlds
    stdin_open: true
    tty: true
volumes:
  terraria-data:
